name: first-action
on:
  pull-request:
  push:
    branches:
      - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        width:
          node-version: "16"
      - name: install dependencies
      - run: npm install
      - name: build project
      - run: npm run build
      - name: aws deploy
      - run: BUILD_DIRECTORY=build BUCKET_NAME=unit-converter-oxygen AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} npm run deploy-aws
